on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# This name will be displayed under "Actions -> Workflows" of github
name: Code Coverage

jobs:
  coverage_report:
    name: Coverage report
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Compile
      run: make CFLAGS=--coverage
    - name: Create gcda files by program execution
      run: ./thermodyn_cycle 1
    - name: Collect Coverage
      run: |
        sudo apt-get -y install lcov
        mkdir -p ./coverage
        geninfo ./ -b ./ -o ./coverage/lcov.info
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: ./coverage/lcov.info
        minimum-coverage: 60
        artifact-name: code_coverage_report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./
        update-comment: true
